repositories:
  acdcserver:
    dmwm: admin
  cc7:
    cmssw: admin
  cc8:
    cmssw: write
  cms:
    cmssw: write
  cmsmon:
    dmwm: admin
  cmsmon-alerts:
    dmwm: admin
  udp-server:
    dmwm: admin
teams:
  cmssw:
  - tulamor
  - cmsuser
  - smuzaffar
  dmwm:
  - muhammadimranfarooqi
  - yuyiguo
  - ericvaandering
  - bbockelm
  - veknet
  - fabioespinosa
  - sbelforte
  - ddaina
  owners:
  - cmsblddoc
  - smuzaffar
  - bbockelm
